### ISSUE TITLE
Unable to add image

### ISSUE THREAD

**Issue by siegfriedcw** [lrsjng/kjua#15]
First and foremost: kjua is a great piece of software, thanks for sharing!

However I've been spending some hours now to figure out how to add a background image.
It works perfectly on the demo page, but the documentation is not clear on what the option "image:" is expecting instead of "null".
I tried a base64 encoded string and just a simple url to an SVG file. Both failed.

Also, after browsing through the issues I just learned that it does not work with IE11. Sadly many corporations still use it (including my current employer), hence at least some mention in the documentation would be great. It would have spared me from burning time why it only works with Chromium, Vivaldi, Edge and Firefox.

Would be great if the documentation could be updated. THANKS!

**Comment by qq382724935** [comment]
I tried many ways too, but uploading images was not effective。。。。
I tried to upload HTMLElement objects.
error:canvas Cannot read property 'naturalWidth' of null

**Comment by martinschilliger** [comment]
Maybe the [Demo](https://larsjung.de/kjua/latest/demo/) can bring you some clarification. The image gets uploaded (as blob) and inserted in a html-element.
`<img id="img-buffer" src="data:image/jpeg;base64,/9j/4AAQSkZJxxxxxxxx…">`
Before it had a URL as source:
`<img id="img-buffer" src="dummy.png">`

In the `update_qrcode()` function of [scripts.js](https://larsjung.de/kjua/latest/demo/scripts.js) you can read on line 84:
`image: el_by_id('img-buffer')`

`el_by_id` itself isn't magic, it just returns the element.
```javascript
function el_by_id(id) {
  return doc.getElementById(id);
}
```

So that means you should pass an actual `<img>` element to image: and it will work. Hope that helps you. 😊

**Comment by werthdavid** [comment]
Since the owner of the repo seems to be not actively maintaining it, I created a fork that is published in NPM as kjua-svg (it comes with svg support).
https://github.com/werthdavid/kjua
You can open an issue/feature-request there or even an Pull-request.

**Comment by werthdavid** [comment]
kjua-svg@1.7.0 supports adding base64-string as image. Not tested with IE11 though

**Comment by lrsjng** [comment]
@martinschilliger 's answere is the way to go here..
